### ISSUE TITLE
It does not work for Silex 2.0.x

### ISSUE THREAD

**Issue by AVBIT** [icehero/silex-opauth#13]
ERROR:
ClassNotFoundException in OpauthExtension.php line 11:
Attempted to load interface "ServiceProviderInterface" from namespace "Silex".
Did you forget a "use" statement for "Pimple\ServiceProviderInterface"?

Sorry for the stupid question ... How to fix it (adapt)?

**Comment by icehero** [comment]
hey @AVBIT, I'm not sure how to help you. There are no plans to upgrade this package, but if you want you can give it a try, because it shouldn't be too hard to do an upgrade.

thank you.
