### ISSUE TITLE
Error after request callback

### ISSUE THREAD

**Issue by silverpark** [icehero/silex-opauth#7]
HI,

I've an error about step of login Callback :

ContextErrorException in OpauthExtension.php line 50:
Notice: Undefined index: opauth

1. in OpauthExtension.php line 50
2. at ErrorHandler->handleError('8', 'Undefined index: opauth', '/home/ubuntu/workspace/vendor/icehero/silex-opauth/src/SilexOpauth/OpauthExtension.php', '50', array('Opauth' => object(Opauth))) in OpauthExtension.php line 50
3. at OpauthExtension->loginCallback() in OpauthExtension.php line 33
4. at OpauthExtension->SilexOpauth\{closure}()
5. at call_user_func_array(object(Closure), array()) in HttpKernel.php line 145
6. at HttpKernel->handleRaw(object(Request), '1') in HttpKernel.php line 66
7. at HttpKernel->handle(object(Request), '1', true) in Application.php line 543
8. at Application->handle(object(Request)) in Application.php line 520
9. at Application->run() in index_dev.php line 22

missing something ?

**Comment by silverpark** [comment]
Line 50 of OpauthExtension, I not receive 'code' in POST but in GET

**Comment by icehero** [comment]
Could you paste part of you configuration that's relevant?

**Comment by silverpark** [comment]
Yes, I have add for config : 

```
// Configure opauth
$app['opauth'] = array(
  'login' => '/auth/login', // Generates a path /auth/login/{strategy}
  'callback' => '/auth/callback',
  'config' => array(
    'security_salt' => 'd41d8cd98f00b204e9800998ecf8427e',
    'Strategy' => array(
        'GitHub' => array(
           'app_id' => '718b6dd54c8d1d3ad',
           'app_secret' => '27884021f5257c13373e14301c54c8ed'
         ),
    )
  )
);

// Enable extension
$app->register(new OpauthExtension($app));

// Listen for events
$app->on(OpauthExtension::EVENT_ERROR, function($e) {
    $this->log->error('Auth error: ' . $e['message'], ['response' => $e->getSubject()]);
    $e->setArgument('result', $this->redirect('/'));
});

$app->on(OpauthExtension::EVENT_SUCCESS, function($e) {
    $response = $e->getSubject();

    /*
       find/create a user, oauth response is in $response and it's already validated!
       store the user in the session
    */
    
    $e->setArgument('result', $this->redirect('/'));
});
```

From my template : 

```
<a href="https://github.com/login/oauth/authorize?client_id=718b6dd54c8d1d3ad&redirect_uri=xxx&scope=user:email&state=" class="service github" target="_top">
```

**Comment by icehero** [comment]
First of all, please reset your GitHub application's client_id & client_secret as soon as possible. You posted sensitive data here.

As documented here https://github.com/opauth/github, you need to change app_id and app_secret into client_id & client_secret. Scope needs to be added after that.

Your login URL is /auth/login/github (the one that you need to click in the frontend) and the callback URL (that needs to be configured in the GitHub Dashboard) is /auth/login/github/oauth2callback or leave empty.

I've tested this last night and it seem to work

**Comment by silverpark** [comment]
Don't worry, it's a wrong data.

I've changed config and I supposed that ```/auth/login/``` is changed by```/auth/login/{strategy} ```
```
$app['opauth'] = array(
  'login' => '/auth/login/', 
  'callback' => '/auth/login/{strategy}/oauth2callback',
```

It's ok but I'm redirected to ```/auth/login/github/oauth2callback?code=xxx``` but this page is not found. Your project don't support this url for [Providing a callback](https://developer.github.com/guides/basics-of-authentication/#providing-a-callback)

What is missing?

**Comment by icehero** [comment]
Keep those two keys `login` & `callback` as in the first example. Set the App's callback from the GitHub dashboard to empty and see what happens.

**Comment by silverpark** [comment]
Github said ```Url can't be blank``` and ```Callback Url can't be blank```, when I add Homepage URL from dashboard of github only, github add the same url of Homepage URL to Authorization callback URL.

I've tested and not work with that.

**Comment by icehero** [comment]
Just leave the callback url the same as the domain.

I've tested on `http://localhost:8000` with the example script from the example folder with only 3 lines changed. https://github.com/icehero/silex-opauth/blob/master/example/example.php#L18-L20

```
        'GitHub' => array( // Is available at /auth/login/github
           'client_id' => 'YOUR_CLIENT_ID',
           'client_secret' => 'YOU_CLIENT_SECRET'
```

And in the GitHub Application dashboard under `Homepage URL` and `Authorization callback URL` I have both to `http://locahost:8000`. This should work.

Also make sure you installed `https://github.com/opauth/github`

**Comment by icehero** [comment]
Just leave the callback url the same as the domain.

I've tested on `http://localhost:8000` with the example script from the example folder with only 3 lines changed. https://github.com/icehero/silex-opauth/blob/master/example/example.php#L18-L20

```
        'GitHub' => array( // Is available at /auth/login/github
           'client_id' => 'YOUR_CLIENT_ID',
           'client_secret' => 'YOU_CLIENT_SECRET'
```

And in the GitHub Application dashboard under `Homepage URL` and `Authorization callback URL` I have both to `http://locahost:8000`. This should work.

Also make sure you installed `https://github.com/opauth/github`

**Comment by silverpark** [comment]
Sorry, It don't work

My composer is ok : 
```
"icehero/silex-opauth":"dev-master",
"opauth/github": "*"
```

1. If I use ```/auth/login/github``` for authentication from github It don't work because the url ```/auth/login/github``` not exist
2. If I use ```https://github.com/login/oauth/authorize?client_id=xxx&redirect_uri=xxx&scope=user:email&state=``` for authentication from github It don't work because I am redirected to ```/?code=xxx```

What do you use like url to login in front ?

**Comment by icehero** [comment]
I login with `/auth/login/github` and that url should exist. You shouldn't hit the URL that you have pasted under 2 directly. Just paste `http://yourlocalapp:port/auth/login/github` and if your config is ok you should be redirected to GitHub.

I know this might be getting annoying, but start in another folder and try to reproduce the steps in my last comment. I'm doing my best here to help you.

I've run the script with `php -S localhost:8000 example/example.php`.

**Comment by silverpark** [comment]
I've : 

```
$app['opauth'] = array(
  'login' => '/auth/login/',
  'callback' => '/auth/login/{strategy}/oauth2callback',
```

What is your config opauth login and callback in silex?

**Comment by icehero** [comment]
Keep callback as `/auth/callback` there. I said only 3 lines need to be edited.

**Comment by silverpark** [comment]
Ok url ```/auth/login/github``` exist now and work.

After login ```/auth/login/github```, I'm redirected to :
```
/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch
```

**Comment by icehero** [comment]
Ok, that's great! Next you have to edit Application's config from the Dashboard. Focus on this part.

You either have the `Authorization callback URL` to `http://localhost:8000` or `http://localhost:8000/auth/login/github/oauth2callback`. They both worked when I tested.

I'm not really sure, but you can try changing the `Homepage URL` to you development URL if the above doesn't work.

**Comment by silverpark** [comment]
My url callback ```https://xxx.io/auth/login/github/oauth2callback``` work because when I go to ```https://xxx.io/auth/login/github/oauth2callback``` I'm redirected to ```https://xxx.io/auth/callback```

Now, when I add in Callback url from dashboard ```https://xxx.io/auth/login/github/oauth2callback```, I'm redirected to ```https://xxx.io/auth/callback``` with an error receive in the listen event ```$app->on(OpauthExtension::EVENT_ERROR...```: 

Error : 
```
array(2) {
  ["error"]=>
  array(3) {
    ["code"]=>
    string(20) "oauth2callback_error"
    ["raw"]=>
    array(3) {
      ["error"]=>
      string(21) "redirect_uri_mismatch"
      ["error_description"]=>
      string(77) "The redirect_uri MUST match the registered callback URL for this application."
      ["error_uri"]=>
      string(60) "https://developer.github.com/v3/oauth/#redirect-uri-mismatch"
    }
    ["provider"]=>
    string(6) "GitHub"
  }
  ["timestamp"]=>
  string(25) "2015-02-10T13:56:38+00:00"
}
```

**Comment by icehero** [comment]
Any news on this?

**Comment by silverpark** [comment]
I'm sorry, it not work. I will use an other oauth for silex. 

Thank you very much for your help and your patient :) :+1:

**Comment by icehero** [comment]
If you found a better and simpler solution, please say. Someone could stumble upon this issue and it could help him in the future.
